-- =============================================================================
-- PL/SQL Object Type: API_RESPONSE_T
-- Generated from OpenAPI model 'ApiResponse'
-- Description: Describes the result of uploading an image resource
-- Generated by 'openapi-generator' ('plsql-server' generator)
-- https://openapi-generator.tech/docs/generators/plsql-server
-- =============================================================================

-- ---------------------------------------------------------------------------
-- DROP statements (uncomment to use)
-- ---------------------------------------------------------------------------
-- DROP TYPE API_RESPONSE_TAB_T FORCE;
-- DROP TYPE API_RESPONSE_T FORCE;

-- ---------------------------------------------------------------------------
-- Object type definition
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TYPE API_RESPONSE_T AS OBJECT (
  code    NUMBER(10),
  type    VARCHAR2(4000),
  message VARCHAR2(4000)
);
/

-- ---------------------------------------------------------------------------
-- Nested-table collection type
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TYPE API_RESPONSE_TAB_T AS TABLE OF API_RESPONSE_T;
/

