-- =============================================================================
-- PL/SQL Object Type: CATEGORY_T
-- Generated from OpenAPI model 'Category'
-- Description: A category for a pet
-- Generated by 'openapi-generator' ('plsql-server' generator)
-- https://openapi-generator.tech/docs/generators/plsql-server
-- =============================================================================

-- ---------------------------------------------------------------------------
-- DROP statements (uncomment to use)
-- ---------------------------------------------------------------------------
-- DROP TYPE CATEGORY_TAB_T FORCE;
-- DROP TYPE CATEGORY_T FORCE;

-- ---------------------------------------------------------------------------
-- Object type definition
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TYPE CATEGORY_T AS OBJECT (
  id   NUMBER(19),
  name VARCHAR2(4000)
);
/

-- ---------------------------------------------------------------------------
-- Nested-table collection type
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TYPE CATEGORY_TAB_T AS TABLE OF CATEGORY_T;
/

