-- =============================================================================
-- PL/SQL Object Type: ORDER_T
-- Generated from OpenAPI model 'Order'
-- Description: An order for a pets from the pet store
-- Generated by 'openapi-generator' ('plsql-server' generator)
-- https://openapi-generator.tech/docs/generators/plsql-server
-- =============================================================================

-- ---------------------------------------------------------------------------
-- DROP statements (uncomment to use)
-- ---------------------------------------------------------------------------
-- DROP TYPE ORDER_TAB_T FORCE;
-- DROP TYPE ORDER_T FORCE;

-- ---------------------------------------------------------------------------
-- Object type definition
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TYPE ORDER_T AS OBJECT (
  id         NUMBER(19),
  pet_id     NUMBER(19),
  quantity   NUMBER(10),
  ship_date  TIMESTAMP,
  status     VARCHAR2(4000), -- ENUM: placed, approved, delivered
  complete   VARCHAR2(1)     -- Y/N
);
/

-- ---------------------------------------------------------------------------
-- Nested-table collection type
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TYPE ORDER_TAB_T AS TABLE OF ORDER_T;
/

