-- =============================================================================
-- PL/SQL Object Type: PET_T
-- Generated from OpenAPI model 'Pet'
-- Description: A pet for sale in the pet store
-- Generated by 'openapi-generator' ('plsql-server' generator)
-- https://openapi-generator.tech/docs/generators/plsql-server
-- =============================================================================

-- NOTE: PET_T depends on CATEGORY_T and TAG_TAB_T.
--       Ensure those types are created first.

-- ---------------------------------------------------------------------------
-- DROP statements (uncomment to use)
-- ---------------------------------------------------------------------------
-- DROP TYPE PET_TAB_T FORCE;
-- DROP TYPE PET_T FORCE;

-- ---------------------------------------------------------------------------
-- Object type definition
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TYPE PET_T AS OBJECT (
  id          NUMBER(19),
  category    CATEGORY_T,
  name        VARCHAR2(4000),
  photo_urls  CLOB,
  tags        TAG_TAB_T,
  status      VARCHAR2(4000) -- ENUM: available, pending, sold
);
/

-- ---------------------------------------------------------------------------
-- Nested-table collection type
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TYPE PET_TAB_T AS TABLE OF PET_T;
/

