-- =============================================================================
-- PL/SQL Object Type: TAG_T
-- Generated from OpenAPI model 'Tag'
-- Generated by 'openapi-generator' ('plsql-server' generator)
-- https://openapi-generator.tech/docs/generators/plsql-server
-- =============================================================================

-- ---------------------------------------------------------------------------
-- DROP statements (uncomment to use)
-- ---------------------------------------------------------------------------
-- DROP TYPE TAG_TAB_T FORCE;
-- DROP TYPE TAG_T FORCE;

-- ---------------------------------------------------------------------------
-- Object type definition
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TYPE TAG_T AS OBJECT (
  id   NUMBER(19),
  name VARCHAR2(4000)
);
/

-- ---------------------------------------------------------------------------
-- Nested-table collection type
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TYPE TAG_TAB_T AS TABLE OF TAG_T;
/

