-- =============================================================================
-- PL/SQL Object Type: USER_T
-- Generated from OpenAPI model 'User'
-- Description: A User who is purchasing from the pet store
-- Generated by 'openapi-generator' ('plsql-server' generator)
-- https://openapi-generator.tech/docs/generators/plsql-server
-- =============================================================================

-- ---------------------------------------------------------------------------
-- DROP statements (uncomment to use)
-- ---------------------------------------------------------------------------
-- DROP TYPE USER_TAB_T FORCE;
-- DROP TYPE USER_T FORCE;

-- ---------------------------------------------------------------------------
-- Object type definition
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TYPE USER_T AS OBJECT (
  id          NUMBER(19),
  username    VARCHAR2(4000),
  first_name  VARCHAR2(4000),
  last_name   VARCHAR2(4000),
  email       VARCHAR2(4000),
  password    VARCHAR2(4000),
  phone       VARCHAR2(4000),
  user_status NUMBER(10)
);
/

-- ---------------------------------------------------------------------------
-- Nested-table collection type
-- ---------------------------------------------------------------------------
CREATE OR REPLACE TYPE USER_TAB_T AS TABLE OF USER_T;
/

